#!/bin/bash

INFOS=$(nvidia-smi --query-gpu=utilization.gpu,utilization.memory,memory.total,memory.free,memory.used --format=csv | tail -1)

# remove all whitespaces
INFOS="$(echo -e "${INFOS}" | tr -d '[:space:]')"

IFS=, read -ra vals <<< "$INFOS"


GPU_UTIL="${vals[0]}"
GPU_MEMORY_UTIL="${vals[1]}"
GPU_MEMORY_TOTAL="${vals[2]}"
GPU_MEMORY_FREE="${vals[3]}"
GPU_MEMORY_USED="${vals[4]}"

MEM_USED_INTEGER=$(echo $GPU_MEMORY_USED | tr -d 'MiB')
MEM_TOTAL_INTEGER=$(echo $GPU_MEMORY_TOTAL | tr -d 'MiB')

MEM_FREE_PERCENT=`bc <<< "scale=0; 100 * $MEM_USED_INTEGER / $MEM_TOTAL_INTEGER "`

GPU_SYMBOL_UTIL=""
GPU_SYMBOL_MEMORY=""


printf "%s %3s %s %s%%" $GPU_SYMBOL_UTIL $GPU_UTIL $GPU_SYMBOL_MEMORY $MEM_FREE_PERCENT
#echo "$GPU_SYMBOL_UTIL $GPU_UTIL $GPU_SYMBOL_MEMORY ${MEM_FREE_PERCENT}%"
