#!/bin/bash
# using openweather to get data

APIKEY="APIKEY"


# this magically does not work. there is no reason because
# since CITY_ID in this case is exactly "CITY" aswell.
# when i3blocks executes the scripts, this is NOT the case however!
#CITY_ID=$(~/.config/i3/scripts/weather/get_city.sh)

CITY_ID="CITY"


URL="http://api.openweathermap.org/data/2.5/weather?q=${CITY_ID}&units=metric&APPID=${APIKEY}"

RESPONSE="`wget -qO- $URL`"

CONDITION=$(echo $RESPONSE | jq .'weather[0].main' | sed 's/"//g')
TEMP="$(echo $RESPONSE | jq .'main.temp')"


WEATHER_TEMP=$(echo "${RESPONSE}" | grep -o -e '\"temp\":\-\?[0-9]*' | awk -F ':' '{print $2}' | tr -d '"')


# if python is present, we use it to round the temperature
which python &>/dev/null
if [[ $? -eq 0 ]]; then
    TEMP=`python -c "print(round($TEMP, 1))"`
fi

#SUN_ICON=
#CLOUD_ICON=
#CLOUD_SHOWER_ICON=
#SNOW_ICON=

ICON_SUNNY=""
ICON_CLOUDY=""
ICON_RAINY=""
ICON_STORM=""
ICON_SNOW=""
ICON_FOG=""


case $CONDITION in
	'Clear')
		WEATHER_ICON=$ICON_SUNNY
		;;
	'Rain')
		WEATHER_ICON=$ICON_RAINY
		;;
	'Clouds')
		WEATHER_ICON=$ICON_CLOUDY
		;;
	'Snow')
		WEATHER_ICON=$ICON_SNOW
		;;
	'Fog')
		WEATHER_ICON=$ICON_FOG
		;;
	'Storm')
		WEATHER_ICON=$ICON_STORM
		;;
	'*')
		WEATHER_ICON="?"
		;;
esac



echo "${WEATHER_ICON} ${TEMP}°C"
